import { Footer } from "../footer/footer";
import { Header } from "../header/header";
import { Menu } from "../menu/menu";
import Head from "next/head";

import layout from "./layout.module.css";

export interface menuItemsI {
  path: string;
  label: string;
}

export function Layout({ children }: { children: any }) {
  const menuItems: Array<menuItemsI> = [
    { path: "/", label: "Inicio" },
    { path: "/todo", label: "Tareas" },
    { path: "/about", label: "Nosotros" },
  ];

  return (
    <div className={layout.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <Menu menuItems={menuItems}></Menu>
      </Header>
      <main className={layout.main}>{children}</main>
      <Footer></Footer>
    </div>
  );
}
